name: fikis_fleet_command
description: A comprehensive Flutter-based Fleet Management mobile app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  flutter_slidable: ^3.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/

