name: fikis_fleet_command
description: A comprehensive Flutter-based Fleet Management mobile app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  flutter_slidable: ^3.1.1

  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
#  assets:
#    - assets/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"   # or any image you have
